#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 24 12:26:57 2021

@author: sjcet
"""

#1. Create a three dimensional array specifying float data type and print it.
import numpy as np
array_3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype='f')
print(array_3D.dtype)
print(array_3D)
